language: node_js
node_js:
  - "8"
sudo: true
dist: trusty

branches:
  only:
  - master

script:
  - npm run build

deploy:
  provider: surge
  project: ./www/
  domain: http://dark-religion.surge.sh/